export { default as Main } from './Main';
export { default as LogIn } from './LogIn';
export { default as Authentication } from './Authentication';
export { default as Home } from './Home';
export { default as Post } from './Post';
export { default as Article } from './Article';
export { default as ArticleDetail } from './Article/ArticleDetail';
export { default as Edit } from './Edit';
export { default as About } from './About';
